spring.application.name=jwt-security


spring.datasource.url=jdbc:mysql://localhost:3306/springjwt
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.jwt.secret=84e049bbcf5b9cd9dbb589a9411f1ed24536082c23b1bc170e78754941239d74
app.jwt.expiration-ms=3600000